Description: >
    Author: Emanuele Giarlini - 
    This template has been developed following the one already used for the second assignment.
    It basically creates an EC2 instance containing Jenkins 

Parameters:
      EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 5.95.215.195/32
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 5.95.215.195/32
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  JenkinsInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo apt-get update -y
            sudo apt install -y default-jdk-headless python3-venv make
            wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
            sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9B7D32F2D50582E6
            sudo add-apt-repository universe
            sudo apt-get update -y
            sudo apt-get install -y jenkins
            sudo systemctl start jenkins
            sudo systemctl enable jenkins
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.5/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint
            #sudo snap install docker
            
            sudo apt-get install docker.io
            sudo usermod -aG docker jenkins

      ImageId: ami-003634241a8fcdec0
      SubnetId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      KeyName: EmaJarKey
      SecurityGroupIds: 
        - !Ref WebServerSecGroup
      InstanceType: t3.micro
      Tags: 
      - 
        Key: "Name"
        Value: "Jenkins"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '20'